---
Name: ecommerce_countries
Before: 'mysite/*'
After: 'framework/*','cms/*', 'ecommerce/*'
---


Product:
  extensions:
    - CountryPrice_BuyableExtension

Member:
  extensions:
    - Distributor_MemberDOD

EcommerceCountry:
  extensions:
    - CountryPrice_EcommerceCountry

EcommerceCurrency:
  exchange_provider_class: ExchangeRateProvider_Dummy
  extensions:
    - CountryPrice_EcommerceCurrency

OrderStep:
  extensions:
    - CountryPrice_OrderStepDOD

Order:
  extensions:
    - CountryPrice_OrderDOD

StoreAdmin:
  managed_models:
    - Distributor


---
Only:
  moduleexists: 'ecommerce_product_variation'
---
ProductVariation:
  extensions:
    - CountryPrice_BuyableExtension
