---
Name: ecommerce_countries
---

Product:
  extensions:
    - CountryPrice_BuyableExtension

Member:
  extensions:
    - Distributor_MemberDOD

EcommerceCountry:
  extensions:
    - EcommerceCountryDOD

StoreAdmin:
  managed_models:
    - Distributor

---
Only:
  moduleexists: 'ecommerce_product_variation'
---
ProductVariation:
  extensions:
    - CountryPrice_BuyableExtension
