
ProductGroup:
  extensions:
    - CountryPrice_CopyPrices

Product:
  extensions:
    - CountryPrice_BuyableExtension
    - CountryPrice_CopyPrices

Member:
  extensions:
    - Distributor_MemberDOD

EcommerceCountry:
  extensions:
    - EcommerceCountryDOD
