---
Name: ecommerce_countries
Before: 'mysite/*'
After: ['framework/*','cms/*', 'ecommerce/*']
---

SiteTree:
  extensions:
    - CountryPrice_SiteTreeExtions

Page_Controller:
  extensions:
    - CountryPrice_Page_Controller_Extension

Product:
  extensions:
    - CountryPrice_BuyableExtension

ProductGroup:
  extensions:
    - CountryPrice_ProductGroup

EcommerceDBConfig:
  extensions:
    - CountryPrice_EcomDBConfig

Member:
  extensions:
    - Distributor_MemberDOD

EcommerceCountry:
  extensions:
    - CountryPrice_EcommerceCountry

EcommerceCurrency:
  exchange_provider_class: ExchangeRateProvider_Dummy
  extensions:
    - CountryPrice_EcommerceCurrency

OrderStep:
  extensions:
    - CountryPrice_OrderStepDOD

Order:
  extensions:
    - CountryPrice_OrderDOD

OrderStatusLog:
  extensions:
    - CountryPrice_OrderStatusLog_AND_OrderAtribute

OrderAtribute:
  extensions:
    - CountryPrice_OrderStatusLog_AND_OrderAtribute

StoreAdmin:
  managed_models:
    - Distributor


OrderFormAddress:
  extensions:
    - CountryPrice_OrderFormAddressExtension

SalesAdmin:
    extensions:
        - SalesAdmin_CountryPrice

SalesAdminExtras:
    extensions:
        - SalesAdmin_CountryPrice

---
Only:
  moduleexists: 'ecommerce_product_variation'
---
ProductVariation:
  extensions:
    - CountryPrice_BuyableExtension

---
Only:
  moduleexists: 'grouped-cms-menu'
---
LeftAndMain:
  menu_groups:
    Shop:
      - distributors
