Director:
  rules:
    "copy-prices//$Action/$ID/": "CountryPrice_CopyPrices_Controller"
    "countrypricetestcontrollerurl//$Action/$ID/$OtherID": "CountryPriceTestController"
    "distributors-admin//$Action/$ID/$OtherID": "CheckAllCountriesAndAllPrices"
