<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8" />
<% base_tag %>
<title>Content Check for: $DistributorTitle</title>
<style>
    /* reset */
    p {margin: 0px; padding: 0px;}
    textarea, input {width: 95%;padding: 3px; }

    /* main teims */
    h1 {text-align: center;}
    .jsActions { margin: 0px; padding: 0px; text-align: right;}
    .jsActions a{font-size: 10px; text-decoration: none;}
    .jsActions a:hover{text-decoration: underline;}
    .jsActions li {display: inline;}
    .jsActions li a.current {color: black; font-weight: bold;}
    h2 {display: inline;}
    #loading {margin: 20px; text-align:center;}
    #wrapper {display: none;}

    /* tree */
    li.treeNode {margin-bottom: 0.5em; margin-top: 0.5em; font-size: 0.95em; list-style: none; clear: right; border-top: 1px solid #ddd; padding-top: 7px;}
    li.item a.openCloseLink:before, li.folder a.openCloseLink:before {
        font-size: 23px;
    }
    li.item a.openCloseLink:before {
        content: "– "
    }
    li.folder a.openCloseLink:before {
        content: "+ "
    }
    a.openCloseLink, a.edit, a.delete-record {
            color: #000000;
            cursor: pointer;
            text-decoration: none;
    }
     a.delete-record{
         display: inline-block;
         margin-left: 5px;
     }
     a.delete-record:hover{
         color: red;
     }
    a.openCloseLink:hover, a.edit:hover {
        color: green;
    }


    /* edit section */
    dl {margin: 0px; padding: 0px;}
    dt {font-weight: bold; text-decoration: none; float: left; width: auto;}
    a.edit {display: block; width: 100%; min-height: 1.5em;}
    dd {display: block; background-color: pink; float: right; width: 65%; margin-bottom: 7px; padding: 12px; border-radius: 5px; margin-left: 0px!important;}
    dd.readonly {background-color: #63B8EE;}
    dd.editable span {float: left; padding-right: 5px;}
    .loading {background: url('cms/images/network-save.gif') no-repeat 140px 6px!important;}
        dd.loading input, dd.loading textarea {display: none;}
  .updateMessage {display: block; width: auto;}
  .pricing .valueHolder div {display: inline; float: left; padding-right: 3px;}
  .pricing .editing .valueHolder div.editablePart button, .countryPrices .editing .valueHolder div.editablePart input, .countryPrices .editing .valueHolder div.editablePart a {margin-top: 0px; display: inline;}
  .pricing .editing .valueHolder div.editablePart {margin-top: -8px;}
  .pricing input {width: 5em!important;}

    /* messages */
    .message.good {color: green; }
    .message.bad {color: red;}



    /* button */
button {
    -moz-box-shadow:inset 0px 0px 0px 0px #bee2f9;
    -webkit-box-shadow:inset 0px 0px 0px 0px #bee2f9;
    box-shadow:inset 0px 0px 0px 0px #bee2f9;
    background:-webkit-gradient( linear, left top, left bottom, color-stop(0.05, #63b8ee), color-stop(1, #468ccf) );
    background:-moz-linear-gradient( center top, #63b8ee 5%, #468ccf 100% );
    filter:progid:DXImageTransform.Microsoft.gradient(startColorstr='#63b8ee', endColorstr='#468ccf');
    background-color:#63b8ee;
    -moz-border-radius:5px;
    -webkit-border-radius:15px;
    border-radius:15px;
    border:2px solid #3866a3;
    display:inline-block;
    color:#14396a;
    font-family:arial;
    font-size:15px;
    font-weight:bold;
    padding:4px 35px;
    text-decoration:none;
    text-shadow:1px 1px 0px #7cacde;
    margin-top: 12px;
}button:hover {
    background:-webkit-gradient( linear, left top, left bottom, color-stop(0.05, #468ccf), color-stop(1, #63b8ee) );
    background:-moz-linear-gradient( center top, #468ccf 5%, #63b8ee 100% );
    filter:progid:DXImageTransform.Microsoft.gradient(startColorstr='#468ccf', endColorstr='#63b8ee');
    background-color:#468ccf;
}button:active {
    position:relative;
    top:1px;
}

/* This imageless css button was generated by CSSButtonGenerator.com */
</style>
<link type="text/css" rel="stylesheet" href="/ecommerce_countries/css/jquery-te-1.4.0.css">

</head>
<body>
<h1 class="mainHeader">Content Check for: <i>$DistributorTitle</i></h1>
<div id="wrapper">
    <p class="jsActions">
        <a href="" class="openAll">open all</a> | <a href="" class="closeAll">close all</a> | <a href="Security/logout">> log out</a>
    </p>
    <% if DistributorFilterList %>
    <div id="FilterList" class="jsActions">
        <ul>$DistributorFilterList</ul>
    </div>
    <% end_if %>
    <ul class="mainUL">
        <li class="mainLI">
            <h2>Example</h2>
            <ul class="secondUL" id="Example">
                <li data-name="{&quot;F&quot;:&quot;TESTONLY&quot;}">
                    <dl>
                        <dt>Name of information</dt>
                        <dd class="editable">
                            <div>$DistributorLabel Relevant Content</div>
                            <a href="#" class="edit">click on me to edit...</a>
                        </dd>
                    </dl>
                </li>
                <li>
                    <dl>
                        <dt>Read-Only piece of information</dt>
                        <dd class="readonly">
                            <div>only editable by ADMINISTRATORS</div>
                        </dd>
                    </dl>
                </li>
            </ul>
        </li>
        <li class="mainLI">
            <h2>$DistributorLabel</h2>
            <ul class="secondUL" id="Distributors">
                <% if Distributors %>$Distributors<% else %><li class="message bad">There is no $DistributorLabel information available.</li><% end_if %>
            </ul>
        </li>

        <li class="mainLI">
            <h2>Countries</h2>
            <ul class="secondUL" id="Countries">
                <% if AllowSalesTo %>$AllowSalesTo<% else %><li class="message bad">There is no country information available.</li><% end_if %>
            </ul>
        </li>

        <li class="mainLI">
            <h2>Products</h2>
            <ul class="secondUL" id="Products">
                <% if Products %>$Products<% else %><li class="message bad">There is no product information available.</li><% end_if %>
            </ul>
        </li>
        <li class="mainLI">
            <h2>Currencies</h2>
            <ul class="secondUL" id="Products">
                <% if Currencies %>$Currencies<% else %><li class="message bad">There is no currency information available.</li><% end_if %>
            </ul>
        </li>
    </ul>
</div>

<div class="loading" id="loading">loading ... </div>



<script type="text/javascript" src="http://code.jquery.com/jquery-latest.min.js"></script>
<script type="text/javascript" src="/ecommerce_countries/javascript/jquery-te-1.4.0.min.js" charset="utf-8"></script>


<script type="text/javascript">

    jQuery(document).ready(
        function() {
            editorScript.setupFilters();
            editorScript.initEditing();
            jQuery("#loading").fadeOut(
                "fast",
                function() {
                    jQuery("#wrapper").fadeIn();
                }
            );
        }
    );
    var editorScript = {

        setupFilters:function(){
            jQuery("#FilterList a").click(
                function(e, el){
                    e.preventDefault();
                    jQuery("#FilterList a").removeClass("current");
                    jQuery(this).addClass("current");

                    var name = jQuery(this).attr("data-name");
                    var countries = jQuery(this).attr("data-countries");
                    var countryArray = countries.split(",");
                    jQuery(".gpDistributor").hide();
                    jQuery("."+name).show();
                    jQuery(".gpEcommerceCountry").hide();
                    jQuery.each(
                        countryArray,
                        function( index, value ) {
                            jQuery(".EcommerceCountry"+value).show();
                        }
                    );
                }
            );
        },

        jqteSettings : {
            color: false,
            sup: false,
            sub: false,
            fsize: false,
            formats: [
                ["p","Paragraph"],
                ["h1","Main Heading"],
                ["h2","Secondary Heading"],
                ["h3","Regular Heading"],
                ["h4","Small Heading"]
            ]
            //change: function(){alert("change");},
            //blur: function(){jQuery("textarea").change();}
            //focus: function(){alert("focus");},
        },

        createTree: function() {
            // Find list items representing folders and
            // style them accordingly.  Also, turn them
            // into links that can expand/collapse the
            // tree leaf.
            jQuery("li").addClass("treeNode");
            jQuery('li > ul').each(function(i) {
                    // Find this list's parent list item.
                    var parent_li = $(this).parent('li');
                    // Style the list item as folder.
                    parent_li.addClass('folder');

                    // Temporarily remove the list from the
                    // parent list item, wrap the remaining
                    // text in an anchor, then reattach it.
                    var sub_ul = $(this).remove();
                    parent_li.wrapInner('<a/>').find('a').click(function(event) {
                        // Make the anchor toggle the leaf display.
                        sub_ul.toggle();
                        parent_li.toggleClass("folder");
                        parent_li.toggleClass("item");
                        event.preventDefault();
                    }).addClass("openCloseLink");
                    parent_li.append(sub_ul);
            });

            // Hide all lists except the outermost.
            jQuery('ul ul').hide();

            //create open and close all
            jQuery(".openAll").click(
                function(event){
                    event.preventDefault();
                    jQuery("ul ul").show();
                    jQuery(".folder").addClass("item").removeClass("folder");
                }
            );
            jQuery(".closeAll").click(
                function(event){
                    event.preventDefault();
                    $('ul ul').hide();
                    jQuery(".item").addClass("folder").removeClass("item");
                }
            );
        },

        initEditing: function() {

            //set edtiorWidth
            var ddWidth = parseInt(jQuery(window).width() * 0.6);
            jQuery("dd").css("width", ddWidth+"px")


            //start editing text fields
            jQuery('li[data-name] a.edit').click(
                function(event) {
                    event.preventDefault();
                    var parent = jQuery(this).closest("li");
                    jQuery(parent).addClass("editing");

                    jQuery(".updateMessage").remove();
                    if(jQuery(parent).attr('data-textarea') == 1) {
                        var input = '<textarea rows="5" style="width:100%">' + jQuery(this).html() + '</textarea>';
                        input += '<button type="button" class="updateJQTE">Update</button>';
                        jQuery(this).before(input);
                        jQuery('textarea').jqte(editorScript.jqteSettings);
                    }
                    else {
                        var isNew = jQuery(this).closest('li').hasClass('add-node') ? true : false;
                        if(isNew) {
                            var button = jQuery(this).text();
                            var value = 0;
                        } else {
                            var button = 'Update';
                            var value = jQuery(this).text();
                        }
                        var input = '<input type="text" class="text" value="' + value + '" maxlength="255">';
                        input += '<button type="button">' + button + '</button>';
                        jQuery(this).before(input);
                    }
                    event.preventDefault();
                    jQuery(this).hide();
                }
            );

            //updated text fields
            jQuery(document).on(
                'click',
                'button',
                function() {
                    //set variables
                    var parent = jQuery(this).closest("li[data-name]");
                    jQuery(parent).removeClass('add-node');
                    var data = jQuery.parseJSON(jQuery(parent).attr('data-name'));

                    //removing editors
                    if(jQuery(parent).attr("data-textarea") == 1) {
                        jQuery('textarea').jqte();
                    }

                    //retrieving data
                    var input = jQuery(parent).find("textarea, input, select");
                    data.V = jQuery(input).val();

                    //remove nodes
                    jQuery(input).remove();
                    jQuery(parent).find('button').remove();

                    //start update!
                    jQuery(parent).removeClass('editing');
                    jQuery(parent).addClass('loading');
                    jQuery.get(
                        'distributors-admin/setobjectfield',
                        data,
                        function(result) {
                            var editLink = jQuery(parent).find('a.edit');
                            //var editLink = jQuery(parent).find('a');
                            if(result >= 1) { // Success
                                var action = 'Updated';
                                if(result > 1) {
                                    action = 'Added';
                                    var liHolder = jQuery(parent).closest("li");
                                    var oldValueAsString = jQuery(liHolder).attr('data-name');
                                    var tempObject = JSON.parse(oldValueAsString);
                                    tempObject['I'] = result;
                                    newValueAsString = JSON.stringify(tempObject);
                                    jQuery(liHolder).attr('data-name', newValueAsString);
                                }
                                var message = '<span class="updateMessage message good">' + action + ' successfully.</span>';

                                if(jQuery(parent).closest('li').is('[data-textarea]')) {
                                    jQuery(editLink).html(data.V);
                                }
                                else {
                                    jQuery(editLink).text(data.V);
                                }
                            }
                            else { // Error
                                var message = '<span class="updateMessage message bad">' + result + '.</span>';
                            }
                            //show new elements

                            jQuery(parent).find("dt").append(message);
                            jQuery(editLink).show();
                            jQuery(parent).removeClass('loading');
                            jQuery(liHolder).find(".updateMessage").fadeOut(
                                5000,
                                function() {
                                    jQuery(liHolder).find(".updateMessage").remove();
                                }
                            );
                        }
                    )
                    .fail(function() {alert('An error has occured');});
                }
            );
            jQuery(document).on(
                'click',
                'a.delete-record',
                function() {
                    //set variables
                    var parent = jQuery(this).closest("li[data-name]");
                    var data = jQuery.parseJSON(jQuery(parent).attr('data-name'));


                    //retrieving data
                    data.V = 0;

                    //remove nodes
                    //start update!
                    jQuery(parent).addClass('loading');
                    jQuery.get(
                        'distributors-admin/setobjectfield',
                        data,
                        function(result) {
                            if(result == 'deleted') { // Success
                                var action = 'Deleted';
                                var liHolder = jQuery(parent).closest("li");
                                var oldValueAsString = jQuery(liHolder).attr('data-name');
                                var tempObject = JSON.parse(oldValueAsString);
                                tempObject['I'] = 0;
                                newValueAsString = JSON.stringify(tempObject);
                                jQuery(liHolder).attr('data-name', newValueAsString);
                                var message = '<span class="updateMessage message good">' + action + ' successfully. To add again, please reload page.</span>';
                            }
                            else { // Error
                                var message = '<span class="updateMessage message bad">' + result + '.</span>';
                            }
                            //show new elements

                            jQuery(parent).find("dt").append(message);
                            jQuery(parent).removeClass('loading');
                            jQuery(liHolder).fadeOut(
                                7000,
                                function() {
                                    jQuery(liHolder).remove();
                                }
                            );
                        }
                    )
                    .fail(function() {alert('An error has occured');});
                }
            );
        }
    }

    editorScript.createTree();


</script>

</body>
</html>
